### ISSUE TITLE
brew install doesn't work

### ISSUE THREAD

**Issue by assafshomer** [applicaster/zappifest#59]
```
➜  ~ brew install zappifest
Updating Homebrew...
==> Installing zappifest from applicaster/tap
==> Downloading https://github.com/applicaster/zappifest/archive/0.29.0.tar.gz
Already downloaded: /Users/assaf/Library/Caches/Homebrew/zappifest-0.29.0.tar.gz
==> Downloading https://rubygems.org/gems/commander-4.4.0.gem
Already downloaded: /Users/assaf/Library/Caches/Homebrew/zappifest--commander-4.4.0.gem
==> gem install /Users/assaf/Library/Caches/Homebrew/zappifest--commander-4.4.0.gem --no-document --install-dir /usr/local/Cellar/zappifest/0.29.0/libexec/vendor
==> Downloading https://rubygems.org/gems/mime-types-3.1.gem
Already downloaded: /Users/assaf/Library/Caches/Homebrew/zappifest--mime-types-3.1.gem
==> gem install /Users/assaf/Library/Caches/Homebrew/zappifest--mime-types-3.1.gem --no-document --install-dir /usr/local/Cellar/zappifest/0.29.0/libexec/vendor
==> Downloading https://rubygems.org/gems/diffy-3.1.0.gem
Already downloaded: /Users/assaf/Library/Caches/Homebrew/zappifest--diffy-3.1.0.gem
==> gem install /Users/assaf/Library/Caches/Homebrew/zappifest--diffy-3.1.0.gem --no-document --install-dir /usr/local/Cellar/zappifest/0.29.0/libexec/vendor
==> Downloading https://rubygems.org/gems/terminal-table-1.7.3.gem
Already downloaded: /Users/assaf/Library/Caches/Homebrew/zappifest--terminal-table-1.7.3.gem
==> gem install /Users/assaf/Library/Caches/Homebrew/zappifest--terminal-table-1.7.3.gem --no-document --install-dir /usr/local/Cellar/zappifest/0.29.0/libexec/vendor
==> Downloading https://rubygems.org/gems/inquirer-0.2.1.gem
Already downloaded: /Users/assaf/Library/Caches/Homebrew/zappifest--inquirer-0.2.1.gem
==> gem install /Users/assaf/Library/Caches/Homebrew/zappifest--inquirer-0.2.1.gem --no-document --install-dir /usr/local/Cellar/zappifest/0.29.0/libexec/vendor
🍺  /usr/local/Cellar/zappifest/0.29.0: 504 files, 2.9MB, built in 25 seconds
➜  ~ zappifest init
/Users/assaf/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:409:in `block in require_program': program version required (Commander::Runner::CommandError)
	from /Users/assaf/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:408:in `each'
	from /Users/assaf/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:408:in `require_program'
	from /Users/assaf/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:52:in `run!'
	from /Users/assaf/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/assaf/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/import.rb:5:in `block in <top (required)>'
/Users/assaf/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- inquirer (LoadError)
	from /Users/assaf/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/zappifest/0.29.0/lib/zappifest.rb:5:in `<main>'
➜  ~
```

**Comment by lomudi** [comment]
not relevant anymore.
